name: dart_either_example
description: dart_either_example
publish_to: none
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  built_collection: ^5.1.1
  http: ^1.0.0
  rxdart_ext: ^0.3.0
  lints: 6.1.0
  dart_either:

dependency_overrides:
  dart_either:
    path: ../../dart_either