name: dart_either
description: >
  Either monad for Dart language and Flutter framework.
  Type-safe error handling, railway oriented programming.
  Supports Monad comprehensions, async map, async flatMap.
version: 2.0.0
homepage: https://github.com/hoc081098/dart_either.git
repository: https://github.com/hoc081098/dart_either.git
issue_tracker: https://github.com/hoc081098/dart_either/issues
funding:
  - https://www.buymeacoffee.com/hoc081098

environment:
  sdk: '>=3.0.0 <4.0.0'

topics:
  - hoc081098
  - functional-programming
  - fpdart
  - dartz
  - either

dependencies:
  meta: ^1.7.0
  built_collection: ^5.1.1

dev_dependencies:
  rxdart_ext: ^0.3.0
  lints: ^6.0.0
  test: ^1.25.5

dependency_overrides:
  rxdart_ext: ^0.3.0
